# Generated by Django 4.0.5 on 2022-08-14 02:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spelling', models.CharField(max_length=50, unique=True)),
                ('part_of_speech', models.CharField(max_length=25)),
                ('users', models.ManyToManyField(related_name='words', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
